const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const cats=[
{name:'Tofu',role:'NAP ARCHITECT',bio:'Quiet, observant, and deeply committed to finding the warmest cushion.',mood:'sleepy',pref:'watch first · gentle voices',fur:'#765744'},
{name:'Mochi',role:'CHAOS INTERN',bio:'Investigates shoelaces, bags, and possibly your life choices — on her schedule.',mood:'curious',pref:'play when invited',fur:'#c78c68'},
{name:'Bean',role:'GENTLEMAN',bio:'Approaches when ready. Leaves when he is done. Respects boundaries. Icon.',mood:'steady',pref:'short, predictable interactions',fur:'#92735d'},
{name:'Miso',role:'WINDOW SUPERVISOR',bio:'Believes every window is a documentary and every bird is a breaking-news alert.',mood:'alert',pref:'perches + observation',fur:'#d8a96f'},
{name:'Pixel',role:'PUZZLE ENGINEER',bio:'Will solve a food puzzle and then stare at you as if you were the puzzle.',mood:'engaged',pref:'foraging + problem solving',fur:'#9c9c92'},
{name:'Clover',role:'SOFT LAUNCH',bio:'A shy resident who prefers quiet corners and visitors who understand the art of waiting.',mood:'shy',pref:'retreat spaces + no chasing',fur:'#f0eee7'},
{name:'Nori',role:'TOY CRITIC',bio:'Rates every enrichment object with one paw, two blinks, and a dramatic walk away.',mood:'playful',pref:'choice between toys',fur:'#4f4a45'},
{name:'Biscuit',role:'SENIOR CONSULTANT',bio:'Experienced in naps, boundaries, and silently judging badly designed furniture.',mood:'calm',pref:'low traffic + soft resting spots',fur:'#b99d82'}];
const pillars=[
{icon:'🛡️',title:'Safe place',short:'Retreat without being followed.',detail:'Every cat needs a secure place to retreat and rest. In a café, this means protected zones visitors cannot enter or block.'},
{icon:'🍽️',title:'Separated resources',short:'Spread key resources apart.',detail:'Food, water, toileting, resting and scratching resources should not become one crowded resource station.'},
{icon:'🧶',title:'Play + predatory behaviour',short:'Let cats hunt, chase and explore.',detail:'Provide opportunities for play, simulated hunting, foraging and exploration, with choices rather than forced activity.'},
{icon:'🤝',title:'Predictable interaction',short:'Human attention is optional.',detail:'Interaction should be positive, consistent, predictable and tailored to the individual cat’s preferences.'},
{icon:'🌿',title:'Respect the senses',short:'Smell, sound and sight matter.',detail:'Unfamiliar smells, loud sounds and sudden changes can be stressful. Design the room around the cat’s sensory world.'}];
const scenarios=[
{emoji:'😴',title:'A cat is sleeping in a quiet corner.',copy:'Visitors arrive and want a photo. What is the lowest-stress response?',options:['Wake them gently for a photo','Leave the sleeping cat undisturbed','Ask another visitor to wake them'],answer:1,good:'Exactly. Rest is a need, not an interruption waiting to happen.'},
{emoji:'👀',title:'A cat watches you from across the room.',copy:'They have not approached. What is the best opening move?',options:['Walk directly over and pick them up','Pause, stay calm and let them choose','Make a loud kissy noise'],answer:1,good:'Yes. Give the cat information and space rather than removing their control.'},
{emoji:'🚶',title:'A cat walks away during petting.',copy:'The cat has ended the interaction. What now?',options:['Follow so they do not feel ignored','Keep petting because they were enjoying it','Stop and let the exit happen'],answer:2,good:'Boundary respected. A cat leaving is communication, not a challenge.'},
{emoji:'🙈',title:'A shy cat retreats into a hide.',copy:'A visitor says, “But I came to see the cats!”',options:['Open the hide so they can see the cat','Accept that hiding is a valid choice','Tap the hide to encourage them out'],answer:1,good:'Correct. A retreat space only works if the cat can actually use it.'},
{emoji:'🔊',title:'The room suddenly gets loud.',copy:'Several cats move away at once. What is the useful response?',options:['Turn the music up so they get used to it','Reduce the noise and restore a predictable environment','Call the cats back for play'],answer:1,good:'Good read. Reduce the stressor first; do not make the cat adapt to escalating stimulation.'},
{emoji:'🧶',title:'A cat ignores the toy you chose.',copy:'What does that tell you?',options:['They need more encouragement','They have failed the enrichment test','Offer another choice or leave it for later'],answer:2,good:'Exactly. Enrichment is about opportunities and choice, not forcing a response.'}];
let liveData={cafes:[],updated_at:null,pipeline_status:'Loading…'};
function renderCats(){ $('#cat-grid').innerHTML=cats.map((c,i)=>`<article class="cat-card" style="--fur:${c.fur}" data-cat="${i}"><div class="cat-avatar"><div class="cat-body"></div><div class="cat-face"><span></span><span></span></div></div><div class="cat-content"><span class="badge">${c.role}</span><h3>${c.name}</h3><p>${c.bio}</p><div class="cat-meta"><span>${c.mood}</span><span>${c.pref}</span></div></div></article>`).join('');$$('.cat-card').forEach(card=>card.onclick=()=>card.classList.toggle('expanded'));}
function renderPillars(){ $('#pillar-grid').innerHTML=pillars.map((p,i)=>`<article class="pillar" data-pillar="${i}"><div class="pillar-icon">${p.icon}</div><span class="pillar-num">PILLAR 0${i+1}</span><h3>${p.title}</h3><p>${p.short}</p><div class="pillar-detail">${p.detail}</div></article>`).join('');$$('.pillar').forEach(p=>p.onclick=()=>p.classList.toggle('active'));}
function renderCafes(city='all'){const rows=liveData.cafes.filter(x=>city==='all'||x.city===city);$('#cafe-grid').innerHTML=rows.length?rows.map(x=>`<article class="cafe-card"><span class="source-pill">${x.status}</span><h3>${x.name}</h3><p>${x.note}</p><div class="cafe-facts"><span>${x.city}</span><span>${x.area}</span><span>${x.type}</span></div><a class="cafe-link" href="${x.url}" target="_blank" rel="noreferrer">Open source ↗</a></article>`).join(''):`<article class="cafe-card"><h3>No records in this filter yet.</h3><p>The ingestion layer can add them without changing the UI.</p></article>`;}
async function loadLive(){try{const r=await fetch('data/live.json',{cache:'no-store'});if(!r.ok)throw new Error('data unavailable');liveData=await r.json();$('#pipeline-status').textContent=liveData.pipeline_status||'source-aware snapshot';$('#updated-at').textContent=liveData.updated_at?`updated ${new Date(liveData.updated_at).toLocaleString()}`:'';$('#footer-pulse').textContent='data pulse: '+(liveData.pipeline_status||'ready');renderCafes();}catch(e){$('#pipeline-status').textContent='offline · cached demo layer';$('#footer-pulse').textContent='data pulse: offline demo';renderCafes();}}
$$('.filter-chip').forEach(b=>b.onclick=()=>{$$('.filter-chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderCafes(b.dataset.city)});
let designState=new Set();const featureClass={hide:'has-hide',vertical:'has-vertical',resources:'has-resources',enrichment:'has-enrichment',sensory:'has-sensory'};
function updateDesign(){const n=designState.size,pct=n*20;$('#design-score').textContent=pct+'%';$('#design-progress').style.width=pct+'%';$('#welfare-score').textContent=n+' / 5 pillars represented';$('#score-number').textContent=n;const msg=n===0?'Add your first welfare feature.':n===1?'A good start. Add separated resources and more choice.':n===2?'The room is getting kinder. Think about play and sensory load.':n===3?'Strong foundation. Add interaction planning and sensory calm.':n===4?'Almost there — one more pillar rounds out the room.':'All five pillars represented. Now staff practice matters too.';$('#design-feedback').textContent=msg;$('#welfare-message').textContent=msg;const room=$('#room');Object.values(featureClass).forEach(c=>room.classList.remove(c));designState.forEach(f=>room.classList.add(featureClass[f]));}
$$('.design-option').forEach(row=>{row.addEventListener('click',e=>{if(e.target.tagName==='INPUT')return;const input=row.querySelector('input');input.checked=!input.checked;input.dispatchEvent(new Event('change'));});row.querySelector('input').addEventListener('change',e=>{const f=row.dataset.feature;e.target.checked?designState.add(f):designState.delete(f);updateDesign();});});
const signalText={relaxed:'Relaxed signal: keep the interaction gentle and let the cat choose whether to approach.',overloaded:'Possible stress signal: reduce stimulation, create distance and avoid forcing contact.',avoid:'Clear boundary signal: allow the cat to hide or move away. Do not pursue.'};$$('[data-signal]').forEach(b=>b.onclick=()=>$('#signal-result').textContent=signalText[b.dataset.signal]);
let scenarioIndex=0;function renderScenario(){const s=scenarios[scenarioIndex];$('#scenario-count').textContent=String(scenarioIndex+1).padStart(2,'0')+' / '+String(scenarios.length).padStart(2,'0');$('#scenario-emoji').textContent=s.emoji;$('#scenario-title').textContent=s.title;$('#scenario-copy').textContent=s.copy;$('#scenario-feedback').textContent='';$('#scenario-options').innerHTML=s.options.map((o,i)=>`<button class="scenario-option" data-i="${i}">${o}</button>`).join('');$$('.scenario-option').forEach(b=>b.onclick=()=>$('#scenario-feedback').textContent=+b.dataset.i===s.answer?'✓ '+s.good:'Try again — think about choice, predictability and the cat’s ability to opt out.');}$('#next-scenario').onclick=()=>{scenarioIndex=(scenarioIndex+1)%scenarios.length;renderScenario();};
let selected='';$$('.session').forEach(s=>s.onclick=()=>{$$('.session').forEach(x=>x.classList.remove('selected'));s.classList.add('selected');selected=s.dataset.session;});$('#book-demo').onclick=()=>$('#booking-message').textContent=selected?'Demo saved: '+selected+'. No real reservation was made.':'Pick a session first.';
$$('[data-scroll]').forEach(b=>b.onclick=()=>$(b.dataset.scroll).scrollIntoView({behavior:'smooth'}));
const glow=$('.cursor-glow');window.addEventListener('pointermove',e=>{glow.style.left=e.clientX+'px';glow.style.top=e.clientY+'px';if(Math.random()<.035){const p=document.createElement('span');p.className='paw';p.textContent='🐾';p.style.left=e.clientX+'px';p.style.top=e.clientY+'px';document.body.appendChild(p);setTimeout(()=>p.remove(),1100);}});
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('show');}),{threshold:.12});$$('.reveal').forEach(x=>observer.observe(x));renderCats();renderPillars();renderScenario();loadLive();updateDesign();